/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistema.telas;

import br.com.sistema.controller.ConverterData;
import br.com.sistema.controller.Facade;
import br.com.sistema.controller.FacadeAssistente;
import br.com.sistema.modelos.Evento;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reginaldo
 */
public class TelaAssistenteSala extends javax.swing.JFrame {
    ConverterData converter = new ConverterData();
    Facade fachada = new Facade();
    FacadeAssistente fachadaAssistente = new FacadeAssistente();
    boolean mensagem = false;
    /**
     * Creates new form TelaAssistenteSala
     */
    public TelaAssistenteSala() throws SQLException {
        this.setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        URL url = this.getClass().getResource("/imagens/icone.png");  
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo); 
        carregarJTableMaterial();
        carregarJTableBloco();
        carregarJTableSala();
        carregarJTableEvento();
    }

    public void recebeParametros(List lista) {
        nome.setText((String) lista.get(0));
        email.setText((String) lista.get(1));
        logado.setText((String) lista.get(2));
        fachada.exibirImagemLabel((byte[]) lista.get(3), foto);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logado = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        editarPerfil = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        foto = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        Excluir2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        novo2 = new javax.swing.JButton();
        MostrarTodos1 = new javax.swing.JButton();
        Editar2 = new javax.swing.JButton();
        pesquisar1 = new javax.swing.JButton();
        MostrarTodos4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        ExcluirBloco = new javax.swing.JButton();
        EditarBloco = new javax.swing.JButton();
        novoBloco = new javax.swing.JButton();
        MostrarTodosBlocos = new javax.swing.JButton();
        pesquisar2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        novaSala = new javax.swing.JButton();
        MostrarTodasSalas = new javax.swing.JButton();
        EditarSala = new javax.swing.JButton();
        ExcluirSala = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        pesquisar3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        AlocarSala = new javax.swing.JButton();
        DesalocarSala = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        novoEvento = new javax.swing.JButton();
        MostrarTodosEventos = new javax.swing.JButton();
        pesquisar4 = new javax.swing.JButton();
        logado1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N

        nome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel1.setText("Logado como:");

        logado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel2.setText("Nome:");

        jLabel3.setText("E-mail:");

        editarPerfil.setText("Editar Perfil");
        editarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPerfilActionPerformed(evt);
            }
        });

        jButton4.setText("Sair");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Excluir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        Excluir2.setToolTipText("Excluir Material");
        Excluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Excluir2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        novo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar.png"))); // NOI18N
        novo2.setToolTipText("Inserir Material");
        novo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novo2ActionPerformed(evt);
            }
        });

        MostrarTodos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/listar.png"))); // NOI18N
        MostrarTodos1.setToolTipText("Exibir Materiais");
        MostrarTodos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarTodos1ActionPerformed(evt);
            }
        });

        Editar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar3.png"))); // NOI18N
        Editar2.setToolTipText("Editar Material");
        Editar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar2ActionPerformed(evt);
            }
        });

        pesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar2.png"))); // NOI18N
        pesquisar1.setText("Pesquisar");
        pesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisar1ActionPerformed(evt);
            }
        });

        MostrarTodos4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta.png"))); // NOI18N
        MostrarTodos4.setToolTipText("Devolver Material");
        MostrarTodos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarTodos4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(novo2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Editar2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Excluir2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MostrarTodos1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MostrarTodos4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pesquisar1)))
                .addGap(170, 170, 170))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pesquisar1))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Editar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Excluir2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MostrarTodos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MostrarTodos4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(novo2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gerenciar Material", jPanel2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        ExcluirBloco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        ExcluirBloco.setToolTipText("Excluir Bloco");
        ExcluirBloco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirBlocoActionPerformed(evt);
            }
        });

        EditarBloco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar3.png"))); // NOI18N
        EditarBloco.setToolTipText("Editar Bloco");
        EditarBloco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBlocoActionPerformed(evt);
            }
        });

        novoBloco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar.png"))); // NOI18N
        novoBloco.setToolTipText("Cadastrar Bloco");
        novoBloco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoBlocoActionPerformed(evt);
            }
        });

        MostrarTodosBlocos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/listar.png"))); // NOI18N
        MostrarTodosBlocos.setToolTipText("Exibir Blocos");
        MostrarTodosBlocos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarTodosBlocosActionPerformed(evt);
            }
        });

        pesquisar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar2.png"))); // NOI18N
        pesquisar2.setText("Pesquisar");
        pesquisar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(novoBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditarBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExcluirBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MostrarTodosBlocos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pesquisar2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pesquisar2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(novoBloco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditarBloco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExcluirBloco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MostrarTodosBlocos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jTabbedPane1.addTab("Gerenciar Bloco", jPanel1);

        novaSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar.png"))); // NOI18N
        novaSala.setToolTipText("Inserir Material");
        novaSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaSalaActionPerformed(evt);
            }
        });

        MostrarTodasSalas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/listar.png"))); // NOI18N
        MostrarTodasSalas.setToolTipText("Exibir Materiais");
        MostrarTodasSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarTodasSalasActionPerformed(evt);
            }
        });

        EditarSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar3.png"))); // NOI18N
        EditarSala.setToolTipText("Editar Material");
        EditarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarSalaActionPerformed(evt);
            }
        });

        ExcluirSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        ExcluirSala.setToolTipText("Excluir Material");
        ExcluirSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirSalaActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        pesquisar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar2.png"))); // NOI18N
        pesquisar3.setText("Pesquisar");
        pesquisar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(novaSala, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExcluirSala, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MostrarTodasSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(pesquisar3)))
                .addGap(141, 141, 141))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pesquisar3))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(novaSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditarSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExcluirSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MostrarTodasSalas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gerenciar Sala", jPanel3);

        AlocarSala.setIcon(new javax.swing.ImageIcon("D:\\ADS 2016\\NetBeansProjects\\AlocacaoDeSalas-master\\src\\imagens\\alocarSala.png")); // NOI18N
        AlocarSala.setToolTipText("Alocar Sala");
        AlocarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlocarSalaActionPerformed(evt);
            }
        });

        DesalocarSala.setIcon(new javax.swing.ImageIcon("D:\\ADS 2016\\NetBeansProjects\\AlocacaoDeSalas-master\\src\\imagens\\DesalocarSala.png")); // NOI18N
        DesalocarSala.setToolTipText("Desalocar Sala");
        DesalocarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesalocarSalaActionPerformed(evt);
            }
        });

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Título 4", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable5);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        novoEvento.setIcon(new javax.swing.ImageIcon("D:\\ADS 2016\\NetBeansProjects\\AlocacaoDeSalas-master\\src\\imagens\\adicionarEvento.png")); // NOI18N
        novoEvento.setToolTipText("Inserir Evento");
        novoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoEventoActionPerformed(evt);
            }
        });

        MostrarTodosEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/listar.png"))); // NOI18N
        MostrarTodosEventos.setToolTipText("Listar todos os Eventos");
        MostrarTodosEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarTodosEventosActionPerformed(evt);
            }
        });

        pesquisar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar2.png"))); // NOI18N
        pesquisar4.setText("Pesquisar");
        pesquisar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(novoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AlocarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DesalocarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MostrarTodosEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pesquisar4)))
                .addGap(151, 151, 151))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pesquisar4))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(novoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AlocarSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DesalocarSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MostrarTodosEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alocação de Salas", jPanel4);

        logado1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(logado, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(331, 331, 331)
                    .addComponent(logado1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(869, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(logado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarPerfil))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(11, 11, 11))
                            .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3))
                    .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(301, 301, 301)
                    .addComponent(logado1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(248, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void carregarJTableBloco() throws SQLException {
        List<String[]> lista = fachadaAssistente.listarBloco();
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Nome do Bloco");
        

        if (lista.isEmpty()) {
            modelo.addRow(new String[]{"sem dados"});
        }

        for (String[] blocos : lista) {
            modelo.addRow(new String[]{blocos[0]});
        }
        jTable3.setModel(modelo);

    }
    
     public void carregarJTableMaterial() throws SQLException {
        List<String[]> lista = fachadaAssistente.listar();
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Material");
        modelo.addColumn("Tombamento");
        modelo.addColumn("Status");
        modelo.addColumn("Local");

        if (lista.isEmpty()) {
            modelo.addRow(new String[]{"sem dados", null, null, null});
        }

        for (String[] materiais : lista) {
            modelo.addRow(new String[]{materiais[0],
                materiais[1],
                materiais[2]});
        }
        jTable2.setModel(modelo);

    }
     
    public void carregarJTableEvento() throws SQLException {
        List<String[]> lista = fachadaAssistente.listarEvento();
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Data");
        modelo.addColumn("Duração");
        modelo.addColumn("Evento");
        modelo.addColumn("Situação");
        modelo.addColumn("Local");

        if (lista.isEmpty()) {
            modelo.addRow(new String[]{"sem dados", null, null, null, null});
        }

        for (String[] eventos : lista) {
            
            modelo.addRow(new String[]{eventos[0],
                eventos[1],
                eventos[2],
                eventos[3],
                eventos[4]});
        }
        jTable5.setModel(modelo);
    }
    
    public void carregarEditar(String[] lista) throws SQLException{
          String descricao = lista[0];
          Integer tombamento = Integer.parseInt(lista[1]);

                List listaMaterial;
                listaMaterial = fachadaAssistente.retornarMaterial(tombamento);

                if (listaMaterial != null) {
                    EditarMaterial tela;
                    TelaAssistenteSala tela2 = this;
                    tela = new EditarMaterial(tela2, "assistente");
                    tela.recebeParametros(listaMaterial);
                    tela.carregarTexto(true);
                    tela.setVisible(true);

                }
    }

    public void carregarEditarBloco(String[] lista) throws SQLException{
          String descricao = lista[0];
          String num  = lista[1];
          Integer id = Integer.parseInt(num);
          
                List listaBloco;
                listaBloco = fachadaAssistente.retornarBloco(descricao);

                if (listaBloco != null) {
                    EditarBloco tela;
                    TelaAssistenteSala tela2 = this;
                    tela = new EditarBloco(tela2);
                    tela.recebeParametros(listaBloco);
                    tela.carregarTexto(true);
                    tela.setVisible(true);

                }
    }
    
    private void editarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPerfilActionPerformed

        String emailUsuario = email.getText();

        List listaUsuario;
        listaUsuario = fachada.retornarDados(emailUsuario);

        if (listaUsuario != null) {
            Editar tela;
            tela = new Editar();
            try {
                tela.recebeParametros(listaUsuario);
            } catch (SQLException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
            tela.carregarTexto(true);
            tela.setVisible(true);

        }
    }//GEN-LAST:event_editarPerfilActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Excluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Excluir2ActionPerformed
        int[] linhas = jTable2.getSelectedRows();
        if (linhas.length > 1) {
            int resp;
            resp = JOptionPane.showConfirmDialog(null, "Você deseja realmente excluir estes " + linhas.length + " registros?", "Escolha uma opção", JOptionPane.YES_NO_OPTION);
            if (resp == JOptionPane.OK_OPTION) {
                for (int i = 0; i < linhas.length; i++) {
                    int num = i;
                    if (i != 0) {
                        num = 0;
                    }
                    if (linhas[num] != -1) {
                        try {
                            String[] lista = null;
                            try {
                                lista = fachadaAssistente.listar().get(linhas[num]);
                            } catch (SQLException ex) {
                                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                            }

                            String tomb = lista[1];

                            Integer tombamento = Integer.parseInt(tomb);

                            fachadaAssistente.excluirMaterial(tombamento);
                            
                            carregarJTableMaterial();
                    
                            JOptionPane.showMessageDialog(null, linhas.length+" Materiais excluídos!");

                        } catch (SQLException ex) {
                            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Selecione um Material!");
                    }
                }
            }
        } else {
            int linha = jTable2.getSelectedRow();
            if (linha != -1) {

                try {
                    String[] lista = fachadaAssistente.listar().get(linha);

                    String tomb = lista[1];

                    int resp;
                    resp = JOptionPane.showConfirmDialog(null, "Você deseja realmente excluir este registro?", "Escolha uma opção", JOptionPane.YES_NO_OPTION);
                    if (resp == JOptionPane.OK_OPTION) {
                        Integer tombamento = Integer.parseInt(tomb);

                        fachadaAssistente.excluirMaterial(tombamento);
                        JOptionPane.showMessageDialog(null, "Material excluído!");

                        carregarJTableMaterial();
                    } else {
                        JOptionPane.showMessageDialog(null, "Material não foi excluído!");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecione um Material!");
            }

        }
    
    }//GEN-LAST:event_Excluir2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void novo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novo2ActionPerformed
        try {
            CadastrarMaterial tela;
            TelaAssistenteSala tela2 = this;
            tela = new CadastrarMaterial(tela2, "assistente");
            tela.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_novo2ActionPerformed

    private void MostrarTodos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarTodos1ActionPerformed
        try {
            carregarJTableMaterial();
            jTextField2.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MostrarTodos1ActionPerformed

    private void Editar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar2ActionPerformed
        int linha = jTable2.getSelectedRow();
        if (linha != -1) {

            try {
                if(mensagem){
                    String pesq = jTextField2.getText();
                    String[] lista = fachadaAssistente.retornarMaterial(pesq).get(linha);
                    carregarEditar(lista);
                    jTextField2.setText("");
                }else{  
                    String[] lista = fachadaAssistente.listar().get(linha);
                    carregarEditar(lista);
                }

            } catch (SQLException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Material!");
        }
        
        
    }//GEN-LAST:event_Editar2ActionPerformed

    private void pesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisar1ActionPerformed
        String pesq = jTextField2.getText();

        try {
            pesquisarJTable(pesq);
            mensagem = true;
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pesquisar1ActionPerformed

    private void MostrarTodos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarTodos4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarTodos4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void ExcluirBlocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirBlocoActionPerformed
        int[] linhas = jTable3.getSelectedRows();
        if (linhas.length > 1) {
            int resp;
            resp = JOptionPane.showConfirmDialog(null, "Você deseja realmente excluir estes " + linhas.length + " registros?", "Escolha uma opção", JOptionPane.YES_NO_OPTION);
            if (resp == JOptionPane.OK_OPTION) {
                for (int i = 0; i < linhas.length; i++) {
                    int num = i;
                    if (i != 0) {
                        num = 0;
                    }
                    if (linhas[num] != -1) {
                        try {
                            String[] lista = null;
                            try {
                                lista = fachadaAssistente.listarBloco().get(linhas[num]);
                            } catch (SQLException ex) {
                                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                            }

                            String desc = lista[0];

                            fachadaAssistente.excluirBloco(desc);
                            
                            carregarJTableBloco();
                            
                            JOptionPane.showMessageDialog(null, linhas.length+" Blocos excluídos!");
                    

                        } catch (SQLException ex) {
                            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Selecione um Bloco!");
                    }
                }
            }
        } else {
            int linha = jTable3.getSelectedRow();
            if (linha != -1) {

                try {
                    String[] lista = fachadaAssistente.listarBloco().get(linha);

                    String desc = lista[0];

                    int resp;
                    resp = JOptionPane.showConfirmDialog(null, "Você deseja realmente excluir este registro?", "Escolha uma opção", JOptionPane.YES_NO_OPTION);
                    if (resp == JOptionPane.OK_OPTION) {
                        
                        fachadaAssistente.excluirBloco(desc);

                        carregarJTableBloco();
                        JOptionPane.showMessageDialog(null, "Bloco excluído!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Bloco não foi excluído!");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecione um Bloco!");
            }

        }
    }//GEN-LAST:event_ExcluirBlocoActionPerformed

    private void EditarBlocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBlocoActionPerformed
        int linha = jTable3.getSelectedRow();
        if (linha != -1) {

            try {
                if(mensagem){
                    String pesq = jTextField3.getText();
                    String[] lista = fachadaAssistente.retornarBloco(pesq).get(linha);
                    carregarEditar(lista);
                    jTextField3.setText("");
                }else{  
                    String[] lista = fachadaAssistente.listarBloco().get(linha);
                    carregarEditarBloco(lista);
                }

            } catch (SQLException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Material!");
        }
    }//GEN-LAST:event_EditarBlocoActionPerformed

    private void novoBlocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoBlocoActionPerformed
        CadastrarBloco tela;
        TelaAssistenteSala tela2 = this;
        tela = new CadastrarBloco(tela2);
        tela.setVisible(true);
    }//GEN-LAST:event_novoBlocoActionPerformed

    private void MostrarTodosBlocosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarTodosBlocosActionPerformed
        try {
            carregarJTableBloco();
            jTextField3.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MostrarTodosBlocosActionPerformed

    private void pesquisar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisar2ActionPerformed
        String pesq = jTextField3.getText();

        try {
            pesquisarJTableBloco(pesq);
            mensagem = true;
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pesquisar2ActionPerformed

    private void novaSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaSalaActionPerformed
        try {
            CadastrarSala tela = null;
            TelaAssistenteSala tela2 = this;
            try {
                tela = new CadastrarSala(tela2, "assistente");
            } catch (SQLException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
            tela.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_novaSalaActionPerformed

    private void MostrarTodasSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarTodasSalasActionPerformed
        try {
            carregarJTableSala();
            jTextField4.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MostrarTodasSalasActionPerformed

    private void EditarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarSalaActionPerformed
        int linha = jTable4.getSelectedRow();
        if (linha != -1) {

            try {
                if(mensagem){
                    String pesq = jTextField4.getText();
                    String[] lista = fachadaAssistente.retornarSala(pesq).get(linha);
                    carregarEditarSala(lista);
                    jTextField4.setText("");
                }else{
                    String[] lista = fachadaAssistente.listarSala().get(linha);
                    carregarEditarSala(lista);
                }

            } catch (SQLException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Material!");
        }
    }//GEN-LAST:event_EditarSalaActionPerformed

    public void carregarEditarSala(String[] lista) throws SQLException{
          String nome = lista[0];

                List<String[]> listaSala;
                listaSala = fachadaAssistente.retornarSala(nome);

                if (listaSala != null) {
                    EditarSala tela;
                    TelaAssistenteSala tela2 = this;
                    tela = new EditarSala(tela2, "assistente");
                    tela.recebeParametros(listaSala);
                    tela.carregarTexto(true);
                    tela.setVisible(true);

                }
    }
    
    private void ExcluirSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirSalaActionPerformed
        int[] linhas = jTable4.getSelectedRows();
        if (linhas.length > 1) {
            int resp;
            resp = JOptionPane.showConfirmDialog(null, "Você deseja realmente excluir estes " + linhas.length + " registros?", "Escolha uma opção", JOptionPane.YES_NO_OPTION);
            if (resp == JOptionPane.OK_OPTION) {
                for (int i = 0; i < linhas.length; i++) {
                    int num = i;
                    if (i != 0) {
                        num = 0;
                    }
                    if (linhas[num] != -1) {
                        try {
                            String[] lista = null;
                            try {
                                lista = fachadaAssistente.listarSala().get(linhas[num]);
                            } catch (SQLException ex) {
                                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                            }

                            String nome = lista[0];

                            fachadaAssistente.excluirSala(nome);

                            carregarJTableSala();

                        } catch (SQLException ex) {
                            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Selecione uma Sala!");
                    }
                }
            }
            JOptionPane.showMessageDialog(null, linhas.length+" Salas excluídas!");
        } else {
            int linha = jTable4.getSelectedRow();
            if (linha != -1) {

                try {
                    String[] lista = fachadaAssistente.listarSala().get(linha);

                    String nome = lista[0];

                    int resp;
                    resp = JOptionPane.showConfirmDialog(null, "Você deseja realmente excluir este registro?", "Escolha uma opção", JOptionPane.YES_NO_OPTION);
                    if (resp == JOptionPane.OK_OPTION) {

                        if(fachadaAssistente.excluirSala(nome)){
                            JOptionPane.showMessageDialog(null, "Sala excluída!");

                            carregarJTableSala();
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Sala não foi excluída!");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma Sala!");
            }

        }
    }//GEN-LAST:event_ExcluirSalaActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void pesquisar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisar3ActionPerformed
        String pesq = jTextField4.getText();

        try {
            pesquisarJTableSala(pesq);
            mensagem = true;
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pesquisar3ActionPerformed

    private void AlocarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlocarSalaActionPerformed
        int linha = jTable5.getSelectedRow();
        if (linha != -1) {
            
                try {
                    Evento lista = fachadaAssistente.listarEventoCampo().get(linha);
                    String evento = lista.toString();
                    String nome = lista.getNome();
                    AlocarEvento tela;
                    TelaAssistenteSala tela2 = this;
                    tela = new AlocarEvento(tela2, nome);
                    tela.recebeParametros(evento);
                    tela.setVisible(true);
                    carregarJTableEvento();
                } catch (SQLException ex) {
                    Logger.getLogger(TelaAssistenteSala.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(TelaAssistenteSala.class.getName()).log(Level.SEVERE, null, ex);
                }
            
        }
    }//GEN-LAST:event_AlocarSalaActionPerformed

    private void DesalocarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesalocarSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesalocarSalaActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void novoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoEventoActionPerformed
        try {
            InserirEvento tela;
            TelaAssistenteSala tela2 = this;
            tela = new InserirEvento(tela2);
            tela.setVisible(true);
            
//        InserirEvento tela = null;
//        TelaAssistenteSala tela2 = this;
//        tela.setVisible(true);
        
//        InserirEvento evento = new InserirEvento();
//        evento.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(TelaAssistenteSala.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaAssistenteSala.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_novoEventoActionPerformed

    private void MostrarTodosEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarTodosEventosActionPerformed
        
    }//GEN-LAST:event_MostrarTodosEventosActionPerformed

    private void pesquisar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisar4ActionPerformed

    public void pesquisarJTable(String descricao) throws SQLException {
        List<String[]> lista = fachadaAssistente.retornarMaterial(descricao);
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Descrição");
        modelo.addColumn("Tombamento");
        modelo.addColumn("Status");
        modelo.addColumn("Local");

        if (lista.isEmpty()) {
            modelo.addRow(new String[]{"sem dados", null, null, null});
        }

        for (String[] materiais : lista) {
            modelo.addRow(new String[]{materiais[0],
                materiais[1],
                materiais[2]});
        }
        jTable2.setModel(modelo);

    }
    
    public void pesquisarJTableBloco(String descricao) throws SQLException {
        List<String[]> lista = fachadaAssistente.retornarPesquisaBloco(descricao);
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Descrição");

        if (lista.isEmpty()) {
            modelo.addRow(new String[]{"sem dados"});
        }

        for (String[] blocos : lista) {
            modelo.addRow(new String[]{blocos[0]});
        }
        jTable3.setModel(modelo);

    }
    
    public void carregarJTableSala() throws SQLException {
        List<String[]> lista = fachadaAssistente.listarSala();
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Sala");
        modelo.addColumn("Bloco");
        modelo.addColumn("Capacidade");
        modelo.addColumn("Satus");

        if (lista.isEmpty()) {
            modelo.addRow(new String[]{"sem dados", null, null, null});
        }

        for (String[] salas : lista) {
            modelo.addRow(new String[]{salas[0],
                salas[1],
                salas[2]});
        }
        jTable4.setModel(modelo);

    }
    
    public void pesquisarJTableEvento(String NomeEvento) throws SQLException {
        List<String[]> lista = fachadaAssistente.retornarPesquisaEvento(NomeEvento);
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Data");
        modelo.addColumn("Duração");
        modelo.addColumn("Evento");
        modelo.addColumn("Situação");
        modelo.addColumn("Local");

        if (lista.isEmpty()) {
            modelo.addRow(new String[]{"sem dados", null, null, null, null});
        }
        for (String[] eventos : lista) {
        
            modelo.addRow(new String[]{eventos[0],
                eventos[1],
                eventos[2],
                eventos[3],
                eventos[4]});
        }
        jTable5.setModel(modelo);

    }
   
    public void pesquisarJTableSala(String descricao) throws SQLException {
        List<String[]> lista = fachadaAssistente.retornarPesquisaSala(descricao);
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Sala");
        modelo.addColumn("Bloco");
        modelo.addColumn("Capacidade");
        modelo.addColumn("Satus");

        if (lista.isEmpty()) {
            modelo.addRow(new String[]{"sem dados", null, null, null});
        }

        for (String[] salas : lista) {
            modelo.addRow(new String[]{salas[0],
                salas[1],
                salas[2]});
        }
        jTable4.setModel(modelo);

    }
    
    public void atualizarModelo() throws SQLException {
        carregarJTableMaterial();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAssistenteSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAssistenteSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAssistenteSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAssistenteSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaAssistenteSala().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaAssistenteSala.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlocarSala;
    private javax.swing.JButton DesalocarSala;
    private javax.swing.JButton Editar2;
    private javax.swing.JButton EditarBloco;
    private javax.swing.JButton EditarSala;
    private javax.swing.JButton Excluir2;
    private javax.swing.JButton ExcluirBloco;
    private javax.swing.JButton ExcluirSala;
    private javax.swing.JButton MostrarTodasSalas;
    private javax.swing.JButton MostrarTodos1;
    private javax.swing.JButton MostrarTodos4;
    private javax.swing.JButton MostrarTodosBlocos;
    private javax.swing.JButton MostrarTodosEventos;
    private javax.swing.JButton editarPerfil;
    private javax.swing.JLabel email;
    private javax.swing.JLabel foto;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel logado;
    private javax.swing.JLabel logado1;
    private javax.swing.JLabel nome;
    private javax.swing.JButton novaSala;
    private javax.swing.JButton novo2;
    private javax.swing.JButton novoBloco;
    private javax.swing.JButton novoEvento;
    private javax.swing.JButton pesquisar1;
    private javax.swing.JButton pesquisar2;
    private javax.swing.JButton pesquisar3;
    private javax.swing.JButton pesquisar4;
    // End of variables declaration//GEN-END:variables
}
